//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalmBeachScrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASOSSIMILARE
    {
        public int ID { get; set; }
        public string ORIGINALcaseNumber { get; set; }
        public string COMPARAcaseNumber { get; set; }
        public System.DateTime ORIGINALfileDate { get; set; }
        public System.DateTime COMPARAfileDate { get; set; }
        public Nullable<int> IgualesDefendants { get; set; }
        public Nullable<System.DateTime> ORIGINALFinalDate { get; set; }
        public Nullable<System.DateTime> COMPARAFinalDate { get; set; }
        public Nullable<double> SumaDistancia { get; set; }
        public Nullable<double> AVGDISTANCIA { get; set; }
        public Nullable<double> DistanciaFechas { get; set; }
        public string COMPARACION { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<bool> SimilarREVISADO { get; set; }
        public string ORIGINALPlaintiff { get; set; }
        public string COMPARAPlaintiff { get; set; }
    }
}
