//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalmBeachScrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClickPageLog
    {
        public int ID { get; set; }
        public string COUNTY { get; set; }
        public string PAGE { get; set; }
        public System.DateTime TIEMPO { get; set; }
    }
}
