//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalmBeachScrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecloseNegativo
    {
        public System.Guid ID { get; set; }
    }
}
