//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalmBeachScrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINCAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAINCAS()
        {
            this.CASEDOCKETS = new HashSet<CASEDOCKET>();
            this.PARTYNAMES = new HashSet<PARTYNAME>();
        }
    
        public System.Guid ID { get; set; }
        public string COUNTY { get; set; }
        public string CASENUMBER { get; set; }
        public string CASESTATUS { get; set; }
        public string PRIMARY_PARTY { get; set; }
        public string SECONDARY_PARTY { get; set; }
        public System.DateTime FILEDATE { get; set; }
        public string CASETYPE { get; set; }
        public Nullable<bool> FORECLOSURE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public string JUDGE { get; set; }
        public Nullable<int> REVISADO { get; set; }
        public string NOTES { get; set; }
        public Nullable<bool> SUCESSFULLFORECLOSED { get; set; }
        public Nullable<int> WHOMARKEDFORECLOSED { get; set; }
        public Nullable<bool> PARAREVISION { get; set; }
        public Nullable<bool> AI_EVALUATE { get; set; }
        public Nullable<bool> AI_TRAINING { get; set; }
        public Nullable<bool> AI_LABEL { get; set; }
        public Nullable<int> STRCOMPCOUNT { get; set; }
        public Nullable<int> STRCOMPWEIGHT { get; set; }
        public Nullable<int> DISMISSAL { get; set; }
        public Nullable<bool> LightGbm { get; set; }
        public Nullable<double> LightGbmConfidence { get; set; }
        public Nullable<bool> FastTree { get; set; }
        public Nullable<double> FastTreeConfidence { get; set; }
        public Nullable<bool> FastForest { get; set; }
        public Nullable<double> FastForestConfidence { get; set; }
        public Nullable<bool> SdcaLogisticRegression { get; set; }
        public Nullable<double> SdcaLogisticRegressionConf { get; set; }
        public Nullable<bool> ACUERDO { get; set; }
        public Nullable<bool> NOTSERVED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASEDOCKET> CASEDOCKETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTYNAME> PARTYNAMES { get; set; }
    }
}
