//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalmBeachScrapper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CaseEntities : DbContext
    {
        public CaseEntities()
            : base("name=CaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CASEDOCKET> CASEDOCKETS { get; set; }
        public virtual DbSet<MAINCAS> MAINCASES { get; set; }
        public virtual DbSet<PARTYNAME> PARTYNAMES { get; set; }
        public virtual DbSet<repeatedname> repeatednames { get; set; }
        public virtual DbSet<ClickPageLog> ClickPageLogs { get; set; }
        public virtual DbSet<RecordsXdia> RecordsXdias { get; set; }
    }
}
