//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalmBeachScrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTYNAME
    {
        public int ID { get; set; }
        public System.Guid CASEID { get; set; }
        public string COUNTY { get; set; }
        public string CASENUMBER { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public string ATTORNEY { get; set; }
        public Nullable<bool> GARBAGE { get; set; }
        public Nullable<System.DateTime> INSERTED { get; set; }
        public string ATTORNEYCLEAN { get; set; }
    
        public virtual MAINCAS MAINCAS { get; set; }
    }
}
